export const ADVENTURES_ALL = "@@ADVENTURES/ADVENTURES_ALL";
export const ADVENTURES_ALL_ERROR = "@@ADVENTURES/ADVENTURES_ALL_ERROR";

export const ADVENTURE_BY_ID = "@@ADVENTURE/ADVENTURE_BY_ID";
export const ADVENTURE_BY_ID_ERROR = "@@ADVENTURE/ADVENTURE_BY_ID_ERROR";

export const CREATE_ADVENTURE = "@@ADVENTURE/CREATE_ADVENTURE";
export const CREATE_ADVENTURE_ERROR = "@@ADVENTURE/CREATE_ADVENTURE_ERROR";

export const LOGIN = "@@AUTH/LOGIN";
export const LOGIN_ERROR = "@@AUTH/LOGIN_ERROR";
export const LOGOUT = "@@AUTH/LOGOUT";