export const ADVENTURES_ALL = "@@ADVENTURES/ADVENTURES_ALL";
export const ADVENTURES_ALL_ERROR = "@@ADVENTURES/ADVENTURES_ALL_ERROR";

export const ADVENTURE_BY_ID = "@@ADVENTURE/ADVENTURE_BY_ID";
export const ADVENTURE_BY_ID_ERROR = "@@ADVENTURE/ADVENTURE_BY_ID_ERROR";