export enum HttpCodes {
    // SUCCESSFUL
    OK = 200,
    CREATED = 201,
    // CLIENT ERROR
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 401,
    // SERVER ERROR
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    SERVICE_UNAVAILABLE = 503
}